stages:
  - setup
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "marybahati/todo-app"

setup:
  stage: setup
  image: docker:latest
  script:
    - docker --version

build:
  stage: build
  image: node:latest
  script:
    - yarn install
    - yarn run build

deploy:
  stage: deploy
  only:
    - main
  image: docker:latest
  script:
    - echo "Pushing Docker image to Docker Hub"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
