services:
  - docker:dind

stages:
  - build-docker-image
  - push-image-to-docker-hub

variables:
  DOCKER_IMAGE_NAME: "todo-app"
  DOCKER_IMAGE_TAG: "v1.0"

before_script:
  - apt-get update -qy
  - apt-get install -y docker.io
  - docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY_PASSWORD

build-docker-image:
  stage: build-docker-image
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

push-image-to-docker-hub:
  stage: push-image-to-docker-hub
  script:
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG