stages:
  - setup
  - deploy

variables:
  DOCKER_IMAGE_NAME: "marybahati/todo-app"

setup:
  stage: setup
  image: docker:latest
  script:
    - docker --version

deploy:
  stage: deploy
  only:
    - main
  services:
    - docker:24.0.7-dind
  script:
    - echo "Pushing Docker image to Docker Hub"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME