stages:
  - setup
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "marybahati/todo-app"

setup:
  stage: setup
  script:
    - apt-get update -qy
    - apt-get install -y docker.io
    - docker --version

build:
  stage: build
  script:
    - echo "Building Docker image"
    - docker build -t $DOCKER_IMAGE_NAME .

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Pushing Docker image to Docker Hub"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker push $DOCKER_IMAGE_NAME
