
stages:
  - build-docker-image
  - push-image-to-docker-hub

build-docker-image:
  stage: build-docker-image
  script:
    - docker info
    - docker build -t marybahati/todo-app .

push-image-to-docker-hub:
  stage: push-image-to-docker-hub
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker info
    - docker push marybahati/todo-app