stages:
  - deploy

variables:
  DOCKER_IMAGE_NAME: "marybahati/todo-app"

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying to Docker Hub"
    - docker build -t $DOCKER_IMAGE_NAME .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker push $DOCKER_IMAGE_NAME
