services:
  - docker:dind

stages:
  - build-docker-image
  - push-image-to-docker-hub

variables:
  DOCKER_IMAGE_TAG: "v1.0"
  DOCKER_IMAGE_NAME: "marybahati/todo-app"

before_script:
  - apt-get update -qy
  - apt-get install -y docker.io

build-docker-image:
  stage: build-docker-image
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker images

push-image-to-docker-hub:
  stage: push-image-to-docker-hub
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_IMAGE_NAME" --password-stdin
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
