stages:
  - build_and_push_image_to_docker_hub

variables:
  DOCKER_IMAGE_NAME: "marybahati/todo-app"
  DOCKER_IMAGE_TAG: "v1.0"

before_scripts:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_and_push_image_to_docker_hub:
  stage: build_and_push_image_to_docker_hub
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
