apiVersion: apps/v1
kind: Deployment
metadata: 
  name: todo-app
  labels: 
    app: node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
        app: node-deployment
  template:
    metadata:
      labels:
        app: node-deployment
    spec:
      containers:
      - name: todo-app-server
        image: marybahati/todo-app:5507812766
        ports:
        - containerPort: 3000

